version: 2
enable-beta-ecosystems: true
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/util"
    schedule:
      interval: "daily"
  # Maintain dependencies for Gradle Android App
  - package-ecosystem: "gradle"
    directory: "/android"
    schedule:
      interval: "daily"
  # Maintain dependencies for dart (BETA)
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "daily"
