version: 2
enable-beta-ecosystems: true
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    commit-message:
      prefix: "chore(deps-ci)"
      include: "scope"
    schedule:
      interval: "daily"
  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/util"
    commit-message:
      prefix: "build(deps-utl)"
      prefix-development: "chore(deps-utl)"
      include: "scope"
    schedule:
      interval: "daily"
  # Maintain dependencies for Firebase Cloud Functions
  - package-ecosystem: "npm"
    directory: "/firebase/functions"
    commit-message:
      prefix: "build(deps-cf)"
      prefix-development: "chore(deps-cf)"
      include: "scope"
    schedule:
      interval: "daily"
  # Maintain dependencies for Gradle Android App
  - package-ecosystem: "gradle"
    directory: "/android"
    commit-message:
      prefix: "build(deps-and)"
      include: "scope"
    schedule:
      interval: "daily"
  # Maintain dependencies for dart (BETA)
  - package-ecosystem: "pub"
    directory: "/"
    commit-message:
      prefix: "build(deps-flt)"
      prefix-development: "chore(deps-flt)"
      include: "scope"
    schedule:
      interval: "daily"
