image:
  file: .gitpod.Dockerfile

tasks:
  - before: >
      source ~/.bashrc
    init: >
      flutter upgrade && 
      flutter update-packages --force-upgrade &&
      flutter run -d web-server --no-resident && # prebuilds the app
      flutter doctor -v
    command: >
      flutter run -d web-server --web-port=8080 --web-hostname=0.0.0.0 &&
      echo Ready!

ports:
  - port: 8080
    onOpen: open-preview
vscode:
  extensions:
    - Dart-Code.flutter@3.7.1:gujVOCgsbgoN2/po8X1tfA==
    - Dart-Code.dart-code@3.7.1:3XT4xvtPoRdNasA5smNMiA==
