include: package:pedantic/analysis_options.yaml

analyzer:
  plugins:
    - dart_code_metrics

dart_code_metrics:
  anti-patterns:
    - long-method
    - long-parameter-list
  metrics:
    cyclomatic-complexity: 20
    lines-of-executable-code: 50
    number-of-arguments: 8
    maximum-nesting: 5
  metrics-exclude:
    - test/**
  rules:
    - newline-before-return
    - no-boolean-literal-compare
    - no-empty-block
    - prefer-trailing-comma
    - prefer-conditional-expressions
    - no-equal-then-else
    - binary-expression-operand-order
    - double-literal-format
    - member-ordering
    - no-equal-arguments
    - no-object-declaration
    - potential-null-dereference
    - prefer-trailing-comma-for-collection
    - prefer-intl-name
    - provide-correct-intl-args