name: gi_weekly_material_tracker
description: Genshin Impact Weekly Weekly Tracker App

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

# RELEASE USE ONLY. LEAVE COMMENTED OTHERWISE
# flutter build apk --target-platform android-arm64 --split-per-abi
#version: 1.0.0+141

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  about: ^1.4.0
  cached_network_image: ^2.5.0
  cloud_firestore: ^0.16.0
  filesize: ^1.0.4
  firebase_analytics: ^7.0.0
  firebase_auth: ^0.20.0
  firebase_core: ^0.7.0
  firebase_crashlytics: ^0.4.0
  # TODO: Update when available again (https://github.com/mattreid1/firebase_image/issues/23)
  firebase_image:
    git:
      url: git://github.com/thearaks/firebase_image.git
      ref: feature/firebase_storage_6
  firebase_performance: ^0.5.0
  firebase_storage: ^7.0.0
  flutter_rating_bar: ^4.0.0
  flutter_signin_button: ^1.1.0
  flutter_web_browser: ^0.13.1
  get: ^3.24.0
  google_sign_in: ^4.5.6
  material_design_icons_flutter: ^4.0.5755
  octo_image: ^0.3.0
  package_info_plus: ^0.6.3
  path_provider: ^1.6.27
  settings_ui: ^0.6.0
  shared_preferences: '>=0.5.12+4 <2.0.0'
  splashscreen: ^1.3.5
  timezone: ^0.6.1
  transparent_image: ^1.0.0
  url_launcher: ^5.7.10  

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  dependency_validator: ^2.0.1
  flutter_native_splash: ^0.3.1+1
  pedantic: ^1.9.0
  dart_code_metrics: ^2.4.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# Update with flutter pub run flutter_native_splash:create
flutter_native_splash:
  image: assets/logo.png
  color: "ffffff"
  image_dark: assets/logo.png
  color_dark: "000000"

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/images/elements/
    - assets/images/items/
    - assets/logo.png
    - CHANGELOG.md

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  fonts:
    - family: Product-Sans
      fonts:
        - asset: fonts/Product-Sans.ttf
        - asset: fonts/Product-Sans-Italic.ttf
          style: italic
    - family: Product-Sans-Bold
      fonts:
        - asset: fonts/Product-Sans-Bold.ttf
        - asset: fonts/Product-Sans-Bold-Italic.ttf
          style: italic

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
