name: Update Firebase Data

on: 
  push:
    branches:
      - "master"
    paths:
      - "firebase/**/*"
      - "util/**/*"
      - "public/data/**/*"
  workflow_dispatch:

jobs:
  build-utility:
    name: Build Admin Util Tool # From "Build and Test Admin Util" in GitLab CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: npm ci
        working-directory: util
      - run: npm run build --if-present
        working-directory: util
      - run: npm run test --if-present
        working-directory: util
        env:
          CI: true
  changed-files:
    name: Check which files are changed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check if files changed for Realtime DB Banner
        id: rtdb-banner
        uses: tj-actions/changed-files@v24
        with:
          files: |
            public/data/EventBanners.json
            util/**/*
      - name: Set output for Realtime DB Banner
        id: rtdb-banner_out
        if: steps.rtdb-banner.outputs.any_changed == 'true'
        run: |
          echo "::set-output name=any_changed::true"
    outputs:
      rtdb-banner: steps.rtdb-banner_out.outputs.any_changed
  update-rtdb:
    name: Update Realtime DB Game Banners # From "Update Realtime DB Game Banners" in GitLab CI
    runs-on: ubuntu-latest
    needs: [build-utility, changed-files]
    if: needs.changed-files.outputs.rtdb-banner
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js 16
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Extract Service Account Key
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: |
          echo $FIREBASE_SERVICE_ACCOUNT | base64 -d > util/serviceAccountKey.json
          echo $FIREBASE_SERVICE_ACCOUNT | base64 -d > /tmp/sak.json
      - name: Copy Event Banner JSON to Folder
        run: cp public/data/EventBanners.json util
      - run: npm i
        working-directory: util
      - name: Update Firebase Realtime DB Banner Data
        run: npm run updateBanners
        working-directory: util
      - name: Delete SAK
        run: rm /tmp/sak.json

    