# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Generate Debug Flutter Apps (Non-Release)

on: 
  push:
  pull_request:
  workflow_dispatch:

env:
  CI_PIPELINE_IID: ${{ github.run_number }} # Make sure when we actually build release builds it starts from 2009
  CI_COMMIT_REF_NAME: ${{ github.ref_name }}

jobs:
  webapp:
    name: Web App # From "Build Web App" in GitLab CI
    runs-on: ubuntu-latest
    env:
      APP_BUILD_VER: web
      APP_TYPE: Web
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Flutter Stable
        uses: subosito/flutter-action@v2.4.0
        with:
          channel: 'stable'
          cache: true
      - name: Trust GitHub Workspace
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Test Flutter Doctor
        run: flutter doctor -v
      - name: Retrieve Firebase Options Web Dart File and decode it to a file
        env:
          GOOGLE_SVC_DART: ${{ secrets.GOOGLE_SVC_DART }}
        run: echo $GOOGLE_SVC_DART | base64 -d > lib/firebase_options.dart
      - uses: benjlevesque/short-sha@v1.2
        id: short-sha
        with:
          length: 8
      - name: Pre-Setup and obtain version information
        run: |
          export GIT_COMMIT_COUNT="$(git rev-list --count HEAD)"
          echo $GIT_COMMIT_COUNT
          echo $GIT_COMMIT_SHORT_SHA
          chmod +x ./ciscripts/get_version.sh
          ./ciscripts/get_version.sh
        env:
          CI_COMMIT_SHORT_SHA: ${{ steps.short-sha.outputs.sha }}
      - name: Build Flutter App
        run: flutter build web
      - name: Package Artifact
        run: |
          mkdir -p firebase/public
          mv build/web/* ./firebase/public
          zip -r webapp.zip ./firebase/public
      - uses: actions/upload-artifact@v3
        with:
          name: flutter-web-artifact
          path: |
            firebase/
            webapp.zip
  android:
    name: Android Apps # From "Generate Flutter App" in GitLab CI
    runs-on: ubuntu-latest
    env:
      APP_BUILD_VER: dogfood
      APP_TYPE: Android
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Flutter Stable
        uses: subosito/flutter-action@v2.4.0
        with:
          channel: 'stable'
          cache: true
      - name: Install JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - name: Trust GitHub Workspace
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Test Flutter Doctor
        run: flutter doctor -v  
      - name: Retrieve Firebase Options Dart files and decode to file
        env:
          GOOGLE_SVC_ANDROID: ${{ secrets.GOOGLE_SVC_ANDROID }}
          GOOGLE_SVC_DART: ${{ secrets.GOOGLE_SVC_DART }}
        run: |
          echo $GOOGLE_SVC_ANDROID | base64 -d > android/app/google-services.json
          echo $GOOGLE_SVC_DART | base64 -d > lib/firebase_options.dart
      - name: Obtain Debug Keystore from Secrets
        env:
          FLUTTER_KEYSTORE: ${{ secrets.FLUTTER_KEYSTORE }}
          KEY_PROPERTIES: ${{ secrets.KEY_PROPERTIES }}
        run: |
          echo $FLUTTER_KEYSTORE | base64 -d > android/app/flutter.jks
          echo $KEY_PROPERTIES | base64 -d > android/key.properties
      - uses: benjlevesque/short-sha@v1.2
        id: short-sha
        with:
          length: 8
      - name: Pre-Setup and obtain version information
        run: |
          mkdir release
          export GIT_COMMIT_COUNT="$(git rev-list --count HEAD)"
          echo $GIT_COMMIT_COUNT
          echo $GIT_COMMIT_SHORT_SHA
          chmod +x ./ciscripts/get_version.sh
          ./ciscripts/get_version.sh
        env:
          CI_COMMIT_SHORT_SHA: ${{ steps.short-sha.outputs.sha }}
      - name: Build Android Split APK
        run: |
          flutter build apk --target-platform android-arm,android-arm64,android-x64 --split-per-abi
      - name: Move Split APKs to Release folder
        run: mv ./build/app/outputs/apk/release/*.apk ./release
      - name: Build Android Multi-Arch Fat APK
        run: flutter build apk
      - name: Move Fat APK to Release Folder
        run: |
          cp build/app/outputs/apk/release/app-release.apk ./release
          cp build/app/outputs/apk/release/app-release.apk ./app-fatapk.apk
      - uses: actions/upload-artifact@v3
        with:
          name: flutter-android-artifact
          path: |
            release/
            app-fatapk.apk
  ios:
    name: iOS Unsigned IPA
    runs-on: macos-latest
    env:
      APP_BUILD_VER: dogfood
      APP_TYPE: iOS
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Flutter Stable
        uses: subosito/flutter-action@v2.4.0
        with:
          channel: 'stable'
          cache: true
      - name: Trust GitHub Workspace
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Test Flutter Doctor
        run: flutter doctor -v  
      - name: Retrieve Firebase Options Dart files and decode to file
        env:
          GOOGLE_SVC_IOS: ${{ secrets.GOOGLE_SVC_IOS }}
          GOOGLE_SVC_DART: ${{ secrets.GOOGLE_SVC_DART }}
        run: |
          echo $GOOGLE_SVC_IOS | base64 -d > ios/Runner/GoogleService-Info.plist
          echo $GOOGLE_SVC_DART | base64 -d > lib/firebase_options.dart
      - uses: benjlevesque/short-sha@v1.2
        id: short-sha
        with:
          length: 8
      - name: Pre-Setup and obtain version information
        run: |
          mkdir release
          export GIT_COMMIT_COUNT="$(git rev-list --count HEAD)"
          echo $GIT_COMMIT_COUNT
          echo $GIT_COMMIT_SHORT_SHA
          chmod +x ./ciscripts/get_version.sh
          ./ciscripts/get_version.sh
        env:
          CI_COMMIT_SHORT_SHA: ${{ steps.short-sha.outputs.sha }}
      - name: Build iOS Package
        run: flutter build ios --no-codesign
        # run: flutter build ios --release --no-codesign
      - name: Move Package to Release folder
        run: mv ./build/ios/iphoneos/Runner.app ./release
      - name: Generate IPA File
        run: |
          cd release
          mkdir Payload
          cp -r ./Runner.app Payload
          zip -r app.ipa Payload
          cd ..
      - uses: actions/upload-artifact@v3
        with:
          name: flutter-ios-raw-artifact
          path: |
            release/
      - uses: actions/upload-artifact@v3
        with:
          name: flutter-unsigned-ipa-artifact
          path: |
            release/app.ipa
