name: Dart Code SCA to CodeQL

on: 
  push:
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 0 * * 0' # Weekly

jobs:
  dart-analyzer:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    runs-on: ubuntu-latest
    name: Dart Analyzer to CodeQL
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Flutter Stable
        uses: subosito/flutter-action@v2.10.0
        with:
          channel: 'stable'
          cache: true
      - name: Dart Analyze
        run: flutter analyze --write dart_analyze.txt || true
      - name: Dart Analyze to SARIF
        uses: advanced-security/dart-analyzer-sarif@main
        with:
          input: dart_analyze.txt
          output: dart_analyze.sarif
      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: dart_analyze.sarif